on:
  push:
    tags:
    - 'v*'

name: Create Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, 386]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Code
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o build/terraform-backend-git-${{ matrix.os }}-${{ matrix.arch }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: terraform-backend-git
          path: build/terraform-backend-git-${{ matrix.os }}-${{ matrix.arch }}
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: terraform-backend-git
      - name: List Artifacts
        run: |
          echo ::set-env name=ARTIFACTS::$(echo terraform-backend-git/*)
      - name: Release
        uses: docker://antonyurchenko/git-release:v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "true"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "false"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
              ${{ env.ARTIFACTS }}
